### ISSUE TITLE
loosing $ref field data when using isResolveFully option

### ISSUE THREAD

**Issue by lDummyl** [swagger-api/swagger-parser#1166]
Good day! 

I'm using `OpenAPIV3Parser`

I'm trying to parse my openapi: "3.0.2" yaml file

When I have

```parseOptions.isResolveFully = false```

I get
 
```
Services
type: array
items:
  $ref: '#/components/schemas/Service'
```
when i set
```parseOptions.isResolveFully = true```
I get data without any mentioning of the head of the reference (Service):
```
Services
type: array
items:
  required:
  - artifactId
  - description
  - groupId
  - id
  - name
  - version
  properties:
    id:
      type: integer
      format: int64
      readOnly: true
    name:
      type: string
    description:
      type: string
    groupId:
      type: string
    artifactId:
      type: string
    version:
      pattern: (0|(?:[1-9]\d*))(?:\.(0|(?:[1-9]\d*))(?:\.(0|(?:[1-9]\d*)))?(?:\-([\w][\w\.\-_]*))?)?
      type: string
```

reference field becomes `null`. Is there any way to preserve the information about what specificaly referenced type has been Resolved Fully when option is true.
