### ISSUE TITLE
OAS3 scopes attributes is missing in OpenAPI

### ISSUE THREAD

**Issue by ruks** [swagger-api/swagger-parser#1202]
Scopes from securitySchemes flow getting null if an OAS definition is parsed using OAS3 parser. But when try to parser OAS3 definition without scopes says it is not valid. This need to be consistent.

If OAS3 parser makes scopes null it should be validated when parsing same OAS definition. Because same definition can be used to validate again using OAS3 parser.  

```yaml
securitySchemes: 
      default: 
        type: "oauth2"
        flows: 
          implicit: 
            authorizationUrl: "https://test.com"
            scopes: {} // this is getting removed
```
Thanks
