### ISSUE TITLE
BinarySchema V2 to V3 conversion results in StringSchema being used..

### ISSUE THREAD

**Issue by aaronjwhiteside** [swagger-api/swagger-parser#1242]
When using the V3 maven plugin, and a V2 schema with a property such as:

```yaml
          secret:
            type: string
            format: binary
            minLength: 32
```

In https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java#L951

```java
            result = Json.mapper().convertValue(schema, Schema.class);
```

`schema` goes in as `BinarySchema` (v2) and `result` comes out as `StringSchema` (v3)..

This is using swagger-parser-v2-converter 2.0.15.

**Comment by aaronjwhiteside** [comment]
The same issue happens for

```yaml
          secret:
            type: string
            format: byte
```

too... A `ByteArraySchema` should be returned but instead a `StringSchema` is..
