### ISSUE TITLE
Swagger Parser validation failed when the content contains ./ 

### ISSUE THREAD

**Issue by HiranyaKavishani** [swagger-api/swagger-parser#1426]
## Description

When [1] is parsing through swagger, it has been failed due to  ./ which is in **url: ./LICENSE**

Eg:
```
  license:
    name: MIT
    url: ./LICENSE
  title: Brain Web API
  version: v2.17.0
```

## version
swagger-parser-2.0.20

[1] https://github.com/APIs-guru/openapi-directory/blob/master/APIs/intellifi.nl/v2.17.0/openapi.yaml
