### ISSUE TITLE
enum ref requires default properties

### ISSUE THREAD

**Issue by bchazalet** [swagger-api/swagger-parser#143]
Using swagger parser 1.0.13.

In a yaml file, I can't write a an enum definition without a default value.

The following:
``` yaml
  ExampleEnum:
    type: string
    enum:
      - First
      - Second
```
doesn't seem to parse successfully (the ref can't be located in the definitions map).

It took me a couple of hours, but I finally got it to work if I add a default value, i.e. this works:
``` yaml
  ExampleEnum:
    type: string
    default: First
    enum:
      - First
      - Second
```
