### ISSUE TITLE
[bug] For type: date parsed wrong example

### ISSUE THREAD

**Issue by dpolyakov987** [swagger-api/swagger-parser#1500]
For type: date parsed wrong example

### Example
```yaml
components:
  schemas:
    TestDto:
      type: object
      properties:
        universalApplicationId:
          type: string
          format: date
          example: 1987-03-21
```
expected: ```1987-03-21```
but after parsing example: ```Sat Mar 21 03:00:00 MSK 1987```
