### ISSUE TITLE
validator doesn't recognize the `discriminator` type

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-parser#162]
For example:

```yaml
definitions:
  Animal:
    type: object
    discriminator: petType
    description: |
      A basic `Animal` object which can extend to other animal types.
    required:
      - commonName
      - petType
    properties:
      commonName:
        description: the household name of the animal
        type: string
      petType:
        description: |
          The discriminator for the animal type.  It _must_
          match one of the concrete schemas by name (i.e. `Cat`)
          for proper deserialization
        type: string
```

Shows the following:
```
attribute definitions.Animal.discriminator is unexpected
```
