### ISSUE TITLE
Reference resolution fails for project with mix of subfolders and classpath references

### ISSUE THREAD

**Issue by douglasbgray** [swagger-api/swagger-parser#1891]
if a project is configured as follows ...

```text
src/main/resources/
    ├── openapi.yaml
    ├── types/
        ├── local-types.yaml
```

... and a model in `openapi.yaml` has a reference to a model in `local-types.yaml`, and in turn, that model is an alias to a model found in a classpath resource, then the reference is not resolved. 

### Example

**openapi.yaml** (root contract)
```yaml
LocalModel:
  type: object
  properties:
    sharedModelField:
      $ref: 'types/local-types.yaml#/components/schemas/TypesModel'
```

**local-types.yaml** (exists in `types` folder sibling to root contract)
```yaml
TypesModel:
  $ref: '/shared-types.yaml#/components/schemas/SharedModel'
```

**shared-types.yaml** (this is in shared-types.yaml resource in the classpath, not in file system)
```yaml
SharedModel:
  type: object
  properties:
    name:
      type: string
```

The parser attempts to find resolve the reference to `/shared-types.yaml` by prepending the path of the local types directory, so it looks for `types/shared-types.yaml` and does not find it. This leave the reference unresolved.

Since the parser is unable to resolve the references, this affects downstream code generation, which creates invalid types for some properties.

A project with a unit test demonstrating the issue is here - https://github.com/douglasbgray/cp-example

This is first observed in version 2.0.24 and still exists in the most recent version 2.1.12. 

Here is a PR with a fix and corresponding test - https://github.com/swagger-api/swagger-parser/pull/1892
