### ISSUE TITLE
primitive objects don't have properties

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-parser#205]
The parser doesn't like model schemas like this:

```yaml
  Empty:
    type: string
    description: 'Expected empty response could be {}'
```

This is perfectly valid, and properties are not required.
