### ISSUE TITLE
Parsing error with object default value when the nullable true enable

### ISSUE THREAD

**Issue by lnash94** [swagger-api/swagger-parser#2050]
Hi Team,

I'm using OpenAPIV3Parser to get openAPI specifications for the parser version 2.1.16. I am wondering when I used the default value as a null for the object type which is enabled nullable true. It returns below parser issues[1].
is there any particular reason we can not have null as the default in the object type when it is nullable true?

 [1] parser issue
```
attribute components.schemas.CreateChatCompletionRequest.default is not of type `object`
```
example code `logit_bias` field has object type with nullable true enable:

```yml
CreateChatCompletionRequest:
      type: object
      properties:
        ...
        logit_bias:
          type: object
          x-oaiTypeLabel: map
          default: null
          nullable: true
          additionalProperties:
            type: integer
```
