### ISSUE TITLE
validate properties better

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-parser#206]
Currently an invalid property like such:

```
Model:
  properties:
    name:
      type: string
      required: true
```

Is not flagged as invalid.  It should be, as the `required` attribute needs to be an array on the `Model.properties` level.
