### ISSUE TITLE
check for vendor extensions in SecurityDefinitions

### ISSUE THREAD

**Issue by ajayrammohan** [swagger-api/swagger-parser#222]
Hi,

VendorExtensions in SecurityDefinitions are not being deserialized.

```
securityDefinitions:
  JwtAuth_test:
    type: "apiKey"
    name: "auth"
    in: "header"
    x-auth: "someValue"
```
