### ISSUE TITLE
Inline schema's "default", "maximum"... attributes are discarded by parser (or model?)'s ModelImpl class

### ISSUE THREAD

**Issue by QianJin2013** [swagger-api/swagger-parser#239]
When define following parameter with a simple inline schema

```
...
  post:
      ... ...
      parameters:
        - name: amount
          in: body
          schema:
            type: integer
            format: int64
            description: amount of money
            default: 1000
            maximum: 100000
```

I use swagger parser to read the yaml,  it is strange the "default", "maximum"... attributes are disappeared in its ModelImpl instance!

<img width="406" alt="2016-04-29 16 08 54" src="https://cloud.githubusercontent.com/assets/5234060/14910012/b8dcdebc-0e24-11e6-9b30-ac9d14c241a4.png">

Though this is not a big problem, i can have other way to define this attributes, but it's better to let you know this so fix it later.
