### ISSUE TITLE
Consider translate enum types to encompassing types

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-parser#283]
In some cases, users will use the wrong data type for enum values. Considering the following two cases:

```yaml
type: string
enum:
  - true
  - false
```

```yaml
type: integer
enum:
  - "2"
  - "3"
```

In the first example the type is `string` but the values are `boolean` (values need to be explicitly quoted in this case). In the second example the type is `integer` but the values are actually strings.

When it comes to JSON Schema validation, *nothing* will validate against such a definition because both are required to be validated, but it may be safe to assume that the intent of the author was to use the explicit data type as specified by the `type`. To resolve it, the parser can apply the `type` to the values of the enum and avoid potential issues.

Pro:
- Makes the parser (and using tools) more friendly to user errors.

Con:
- May ignore a potentially critical user error.

Consideration:
- Not all cases could be converted, for example:
```yaml
type: integer
enum:
  - 2.1
  - 2.2
```
