### ISSUE TITLE
Resolver with a simple remote ref model doesn't work

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-parser#297]
This scenario:

```yaml
definitions:
  MyModel:
    $ref: 'http://path/to/model/MyModelBase.yaml'
```

Doesn't work, even if the `MyModelBase` exists
