### ISSUE TITLE
Parser dies with object enum values

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-parser#386]
Regardless of support in downstream projects, the parser shouldn't blow up when an enum object appears:

```yaml
enum:
- foo: bar
  baz: bat
```
