### ISSUE TITLE
Undefined but required properties do not fail the validation

### ISSUE THREAD

**Issue by mischac** [swagger-api/swagger-parser#452]
##### Description
The validation does not check whether a required property is actually part of the definition:
A message like `Schema properties specified as 'required' must be defined` is not created for the validation

##### Swagger-codegen version
`2.2.2`

##### Swagger declaration file content or url
In below the version is required but not a property:

```yaml
  Sample:
    required:
      - name
      - version
    properties:
      name:
        type: string
```
