### ISSUE TITLE
Parsing of securitySchemes is not consistent with OAS 3.0.0

### ISSUE THREAD

**Issue by phiz71** [swagger-api/swagger-parser#510]
Hello,

parsing a OAS 3.0.0 spec with this configuration :
```yaml
components
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
```
generates these messages :
```
attribute components.securitySchemes'.api_key'.scheme is missing
attribute components.securitySchemes'.api_key'.flows is missing
attribute components.securitySchemes'.api_key'.openIdConnectUrl is missing
```

Or these attributes are not required for apiKey

The bug is in `io.swagger.parser.v3.util.OpenAPIDeserializer` class, in the `getSecurityScheme` method.
All the `getString` are called with a boolean to determine wether the attribute is required or not. Each boolean should be determined according to the security Type.

Required field for apiKey are : 
 * type, name, in

Required field for http are:
 * type, scheme

Required field for oauth2 are:
 * type, flows

Required field for openIdConnectUrl are:
 * type, openIdConnect
