### ISSUE TITLE
Default Explode value is not correct for query with OAS 3.0.0

### ISSUE THREAD

**Issue by phiz71** [swagger-api/swagger-parser#569]
Hello,

When I parse a OAS 3.0.0 spec with this configuration :
```yaml
parameters:
      - name: tags
        in: query
        description: Tags to filter by
        required: true
        schema:
          type: array
          items:
            type: string
```
The `Parameter.getExplode()` method returns `false`.

Or, since the default style for a query parameter is `form`, the default explode value should be `true` (according to the [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#parameterObject))

Field Name | Type | Description
-- | -- | --
style | string | Describes how the parameter value will be serialized depending on the type of the parameter value. Default values (based on value of in): for **query - form**; for path - simple; for header - simple; for cookie - form.
explode | boolean | When this is true, parameter values of type array or object generate separate parameters for each value of the array or key-value pair of the map. For other types of parameters this property has no effect. **When style is form, the default value is true**. For all other styles, the default value is false.
