### ISSUE TITLE
Reading from remote location fails if relative refs are involved

### ISSUE THREAD

**Issue by marcelstoer** [swagger-api/swagger-parser#650]
Reading a Swagger definition from a remote location fails if it contains relative refs (at the same location). This seems very much related to what @fehguy addressed in #338. I'm on v1.0.34.

I've got a Swagger file at https://somehost/src/main/resources/services/broker-monitor/v1/broker-monitor-service.yaml.

It contains the following snippet

```yaml
...
definitions:
  SomeObject:
    type: object
    ...
      message:
        $ref: '../../../technical-definitions/error-handling/v2/error-model.yaml#/definitions/GeneralError'
```
That referenced definition resides at https://somehost/src/main/resources/technical-definitions/error-handling/v2/error-model.yaml.

If both files are on the local file system then all is well, but reading from the remote location fails with

```
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at io.swagger.parser.util.RefUtils.buildUrl(RefUtils.java:113)
	at io.swagger.parser.util.RefUtils.readExternalUrlRef(RefUtils.java:68)
```

The comment at 
https://github.com/swagger-api/swagger-parser/blob/e8cb13e0f1be80328565e8052c09792cc261c1e8/modules/swagger-parser/src/main/java/io/swagger/parser/util/RefUtils.java#L62 is correct: it _is_ a relative reference. The problem is that it's treated like a _local_ relative reference.
