### ISSUE TITLE
Nesting Definitions to $ref

### ISSUE THREAD

**Issue by lemuelnabong-cwt** [swagger-api/swagger-parser#664]
How to map swagger YAML to java Map that includes mapping of the $ref value from Definitions?

**Comment by gracekarina** [comment]
@lemuel-nabong-cwt-bps sorry I did not get the question, do you have an example? thanks!

**Comment by lemuel-nabong-cwt-bps** [comment]
yaml mapper generate 

```
definitions:
  Product:
    properties:
      product_id:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
  Bag:
    type: array
    items:
      $ref: Product
```

I want to have the real $ref object nested
```
definitions:
  Product:
    properties:
      product_id:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
  Bag:
    type: array
    items:
      Product:
         properties:
           product_id:
             type: string
             description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
```
I wonder if there are method for this or suggestion to best map it, Thanks!

**Comment by gracekarina** [comment]
what if you put instead of : 
```
Bag:
    type: array
    items:
      $ref: Product

```
Bag:
    type: array
    items:
      $ref: '#/Definitions/Product'```
