### ISSUE TITLE
Empty default in schema is parsed as null

### ISSUE THREAD

**Issue by jason-cohen** [swagger-api/swagger-parser#814]
#### Parser version:
2.0.2
#### Description:
OAS 3 spec (partial): 
```yaml
components:
  parameters:
    example:
      name: example
      description: example
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
        default: ''
```

The parameter schema parser treats empty strings as null.

`schema.getDefault()` returns `null`.

The following results in a proper default value being set:
```yaml
components:
  parameters:
    example:
      name: example
      description: example
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
        default: 'a,b,c'
```

`schema.getDefault()` returns `"a,b,c"`.
