### ISSUE TITLE
security requiements object is ignored when the components are in different file

### ISSUE THREAD

**Issue by Ohadbasan** [swagger-api/swagger-parser#940]
##### Description

my open api file is composed of two files.
openapi.yaml
and components.yaml
the paths in my openapi.yaml references the components files.

openapi-generator (javascript) ignores the security field unless I merged the two files
seems like the security field and the components (and their security schemes ) must be in the same file.

##### openapi-generator version

3.3.2

##### OpenAPI declaration file content or url
components.yaml

```
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
```
openapi.yaml
```
security:
  - api_key: []
```
