### ISSUE TITLE
Default values in models are not set in openAPI result

### ISSUE THREAD

**Issue by spacether** [swagger-api/swagger-parser#971]
When one defines a swagger spec with a model per the below yaml
```
definitions:
  TypeHolder:
    type: object
    required:
      - string_item
      - number_item
      - integer_item
      - bool_item
      - array_item
      - object_item
    properties:
      string_item:
        type: string
        default: 'what'
        example: 'what'
      number_item:
        type: number
        default: 1.234
        example: 1.234
      integer_item:
        type: integer
        default: -2
        example: -2
      bool_item:
        type: boolean
        default: true
        example: true
      array_item:
          type: array
          items:
            type: integer
          default:
            - 0
            - 1
            - 2
            - 3
          example:
            - 0
            - 1
            - 2
            - 3
      object_item:
        type: object
        properties:
          id:
            type: integer
            default: 0
            example: 0
          name:
            type: string
            default: "key_val"
            example: "key_val"
```
Default values are returned by the OpenAPIParser for string and bool types only.
Default values are missing for array, integer, and number.

We can see this from the terminal results of swagger-codegen with the -DdebugOpenAPI flag on
```
  "components" : {
    "schemas" : {
      "TypeHolder" : {
        "required" : [ "array_item", "bool_item", "integer_item", "number_item", "object_item", "string_item" ],
        "type" : "object",
        "properties" : {
          "string_item" : {
            "type" : "string",
            "example" : "what",
            "default" : "what"
          },
          "number_item" : {
            "type" : "number",
            "example" : 1.234
          },
          "integer_item" : {
            "type" : "integer",
            "example" : -2
          },
          "bool_item" : {
            "type" : "boolean",
            "example" : true,
            "default" : true
          },
          "array_item" : {
            "type" : "array",
            "example" : [ 0, 1, 2, 3 ],
            "items" : {
              "type" : "integer"
            }
          },
          "object_item" : {
            "type" : "object",
            "properties" : {
              "name" : {
                "type" : "string",
                "example" : "key_val",
                "default" : "key_val"
              },
              "id" : {
                "type" : "integer",
                "example" : 0
              }
            }
          },
```

Adding these definitions will allow the clients to set default values in their models.
This can be helpful in the following use case:
When one is writing an XML model, one needs these defaults to to be set for constant tags.
For example if our xml is:
```xml
<envelope>
<header>constant_value</header>
<body></body>
</envelope>
```
We will need to make a property header, with default=constant_value
Otherwise we require that the clients always pass in header=constant_value

Below are the spec definitions of the defaults

### The swagger 2.0 spec
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md and defines default as 
Schema Section:
default (Unlike JSON Schema, the value MUST conform to the defined type for the Schema Object)

### The openapi 3.02 spec
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md
Schema Section:
default - The default value represents what would be assumed by the consumer of the input as the value of the schema if one is not provided. Unlike JSON Schema, the value MUST conform to the defined type for the Schema Object defined at the same level. For example, if type is string, then default can be "foo" but cannot be 1.

### Server vs Client Library Behavior:
Number, integer, and array defaults were not present in the openAPI results when parsing the spec for output to a server scaffold or a client library.

### Questions
- Can the default key/values be added to model results of all swagger-parsing?
- Can someone point me to where this parsing is done? I am having trouble finding the location in the code base. I am happy to submit a PR to fix this issue if someone can help me find the code doing it.
- When should example be used and when should default be used?

**Comment by spacether** [comment]
Is this issue related?
https://github.com/swagger-api/swagger-core/issues/1568

**Comment by spacether** [comment]
Update:
Integer and number results are present if one includes the format key too.
So instead use the below parameter definitions:
```
      number_item:
        type: number
        format: double
        default: 1.234
      integer_item:
        type: integer
        format: int32
        default: -2
```
